[package]
name = "rustcraft"
version = "0.1.0"
authors = ["Edu Renesto <edure95@gmail.com>"]
edition = "2018"

[dependencies]
glutin = "0.19.0"
gl = "0.11.0"
cgmath = "0.16.1"
stb_image = "0.2.2"
noise = "0.5.1"
